/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Emitted when vesting token claimed by beneficiary */
export type ClaimVestedEvent = {
  poolState: Address;
  beneficiary: Address;
  claimAmount: bigint;
};

export type ClaimVestedEventArgs = {
  poolState: Address;
  beneficiary: Address;
  claimAmount: number | bigint;
};

export function getClaimVestedEventEncoder(): FixedSizeEncoder<ClaimVestedEventArgs> {
  return getStructEncoder([
    ['poolState', getAddressEncoder()],
    ['beneficiary', getAddressEncoder()],
    ['claimAmount', getU64Encoder()],
  ]);
}

export function getClaimVestedEventDecoder(): FixedSizeDecoder<ClaimVestedEvent> {
  return getStructDecoder([
    ['poolState', getAddressDecoder()],
    ['beneficiary', getAddressDecoder()],
    ['claimAmount', getU64Decoder()],
  ]);
}

export function getClaimVestedEventCodec(): FixedSizeCodec<
  ClaimVestedEventArgs,
  ClaimVestedEvent
> {
  return combineCodec(
    getClaimVestedEventEncoder(),
    getClaimVestedEventDecoder()
  );
}
