/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type ConstantCurve = {
  supply: bigint;
  totalBaseSell: bigint;
  totalQuoteFundRaising: bigint;
  migrateType: number;
};

export type ConstantCurveArgs = {
  supply: number | bigint;
  totalBaseSell: number | bigint;
  totalQuoteFundRaising: number | bigint;
  migrateType: number;
};

export function getConstantCurveEncoder(): FixedSizeEncoder<ConstantCurveArgs> {
  return getStructEncoder([
    ['supply', getU64Encoder()],
    ['totalBaseSell', getU64Encoder()],
    ['totalQuoteFundRaising', getU64Encoder()],
    ['migrateType', getU8Encoder()],
  ]);
}

export function getConstantCurveDecoder(): FixedSizeDecoder<ConstantCurve> {
  return getStructDecoder([
    ['supply', getU64Decoder()],
    ['totalBaseSell', getU64Decoder()],
    ['totalQuoteFundRaising', getU64Decoder()],
    ['migrateType', getU8Decoder()],
  ]);
}

export function getConstantCurveCodec(): FixedSizeCodec<
  ConstantCurveArgs,
  ConstantCurve
> {
  return combineCodec(getConstantCurveEncoder(), getConstantCurveDecoder());
}
