/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Emitted when vest_account created */
export type CreateVestingEvent = {
  poolState: Address;
  beneficiary: Address;
  shareAmount: bigint;
};

export type CreateVestingEventArgs = {
  poolState: Address;
  beneficiary: Address;
  shareAmount: number | bigint;
};

export function getCreateVestingEventEncoder(): FixedSizeEncoder<CreateVestingEventArgs> {
  return getStructEncoder([
    ['poolState', getAddressEncoder()],
    ['beneficiary', getAddressEncoder()],
    ['shareAmount', getU64Encoder()],
  ]);
}

export function getCreateVestingEventDecoder(): FixedSizeDecoder<CreateVestingEvent> {
  return getStructDecoder([
    ['poolState', getAddressDecoder()],
    ['beneficiary', getAddressDecoder()],
    ['shareAmount', getU64Decoder()],
  ]);
}

export function getCreateVestingEventCodec(): FixedSizeCodec<
  CreateVestingEventArgs,
  CreateVestingEvent
> {
  return combineCodec(
    getCreateVestingEventEncoder(),
    getCreateVestingEventDecoder()
  );
}
