/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type FixedCurve = {
  supply: bigint;
  totalQuoteFundRaising: bigint;
  migrateType: number;
};

export type FixedCurveArgs = {
  supply: number | bigint;
  totalQuoteFundRaising: number | bigint;
  migrateType: number;
};

export function getFixedCurveEncoder(): FixedSizeEncoder<FixedCurveArgs> {
  return getStructEncoder([
    ['supply', getU64Encoder()],
    ['totalQuoteFundRaising', getU64Encoder()],
    ['migrateType', getU8Encoder()],
  ]);
}

export function getFixedCurveDecoder(): FixedSizeDecoder<FixedCurve> {
  return getStructDecoder([
    ['supply', getU64Decoder()],
    ['totalQuoteFundRaising', getU64Decoder()],
    ['migrateType', getU8Decoder()],
  ]);
}

export function getFixedCurveCodec(): FixedSizeCodec<
  FixedCurveArgs,
  FixedCurve
> {
  return combineCodec(getFixedCurveEncoder(), getFixedCurveDecoder());
}
