/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type LinearCurve = {
  supply: bigint;
  totalQuoteFundRaising: bigint;
  migrateType: number;
};

export type LinearCurveArgs = {
  supply: number | bigint;
  totalQuoteFundRaising: number | bigint;
  migrateType: number;
};

export function getLinearCurveEncoder(): FixedSizeEncoder<LinearCurveArgs> {
  return getStructEncoder([
    ['supply', getU64Encoder()],
    ['totalQuoteFundRaising', getU64Encoder()],
    ['migrateType', getU8Encoder()],
  ]);
}

export function getLinearCurveDecoder(): FixedSizeDecoder<LinearCurve> {
  return getStructDecoder([
    ['supply', getU64Decoder()],
    ['totalQuoteFundRaising', getU64Decoder()],
    ['migrateType', getU8Decoder()],
  ]);
}

export function getLinearCurveCodec(): FixedSizeCodec<
  LinearCurveArgs,
  LinearCurve
> {
  return combineCodec(getLinearCurveEncoder(), getLinearCurveDecoder());
}
