/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/**
 * Represents the different states a pool can be in
 * * Fund - Initial state where pool is accepting funds
 * * Migrate - Pool funding has ended and waiting for migration
 * * Trade - Pool migration is complete and amm trading is enabled
 */

export enum PoolStatus {
  Fund,
  Migrate,
  Trade,
}

export type PoolStatusArgs = PoolStatus;

export function getPoolStatusEncoder(): FixedSizeEncoder<PoolStatusArgs> {
  return getEnumEncoder(PoolStatus);
}

export function getPoolStatusDecoder(): FixedSizeDecoder<PoolStatus> {
  return getEnumDecoder(PoolStatus);
}

export function getPoolStatusCodec(): FixedSizeCodec<
  PoolStatusArgs,
  PoolStatus
> {
  return combineCodec(getPoolStatusEncoder(), getPoolStatusDecoder());
}
