/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getCurveParamsDecoder,
  getCurveParamsEncoder,
  getMintParamsDecoder,
  getMintParamsEncoder,
  getVestingParamsDecoder,
  getVestingParamsEncoder,
  type CurveParams,
  type CurveParamsArgs,
  type MintParams,
  type MintParamsArgs,
  type VestingParams,
  type VestingParamsArgs,
} from '.';

/** Emitted when pool created */
export type PoolCreateEvent = {
  poolState: Address;
  creator: Address;
  config: Address;
  baseMintParam: MintParams;
  curveParam: CurveParams;
  vestingParam: VestingParams;
};

export type PoolCreateEventArgs = {
  poolState: Address;
  creator: Address;
  config: Address;
  baseMintParam: MintParamsArgs;
  curveParam: CurveParamsArgs;
  vestingParam: VestingParamsArgs;
};

export function getPoolCreateEventEncoder(): Encoder<PoolCreateEventArgs> {
  return getStructEncoder([
    ['poolState', getAddressEncoder()],
    ['creator', getAddressEncoder()],
    ['config', getAddressEncoder()],
    ['baseMintParam', getMintParamsEncoder()],
    ['curveParam', getCurveParamsEncoder()],
    ['vestingParam', getVestingParamsEncoder()],
  ]);
}

export function getPoolCreateEventDecoder(): Decoder<PoolCreateEvent> {
  return getStructDecoder([
    ['poolState', getAddressDecoder()],
    ['creator', getAddressDecoder()],
    ['config', getAddressDecoder()],
    ['baseMintParam', getMintParamsDecoder()],
    ['curveParam', getCurveParamsDecoder()],
    ['vestingParam', getVestingParamsDecoder()],
  ]);
}

export function getPoolCreateEventCodec(): Codec<
  PoolCreateEventArgs,
  PoolCreateEvent
> {
  return combineCodec(getPoolCreateEventEncoder(), getPoolCreateEventDecoder());
}
