/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/**
 * Specifies the direction of a trade in the bonding curve
 * This is important because curves can treat tokens differently through weights or offsets
 */

export enum TradeDirection {
  Buy,
  Sell,
}

export type TradeDirectionArgs = TradeDirection;

export function getTradeDirectionEncoder(): FixedSizeEncoder<TradeDirectionArgs> {
  return getEnumEncoder(TradeDirection);
}

export function getTradeDirectionDecoder(): FixedSizeDecoder<TradeDirection> {
  return getEnumDecoder(TradeDirection);
}

export function getTradeDirectionCodec(): FixedSizeCodec<
  TradeDirectionArgs,
  TradeDirection
> {
  return combineCodec(getTradeDirectionEncoder(), getTradeDirectionDecoder());
}
