/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type VestingParams = {
  totalLockedAmount: bigint;
  cliffPeriod: bigint;
  unlockPeriod: bigint;
};

export type VestingParamsArgs = {
  totalLockedAmount: number | bigint;
  cliffPeriod: number | bigint;
  unlockPeriod: number | bigint;
};

export function getVestingParamsEncoder(): FixedSizeEncoder<VestingParamsArgs> {
  return getStructEncoder([
    ['totalLockedAmount', getU64Encoder()],
    ['cliffPeriod', getU64Encoder()],
    ['unlockPeriod', getU64Encoder()],
  ]);
}

export function getVestingParamsDecoder(): FixedSizeDecoder<VestingParams> {
  return getStructDecoder([
    ['totalLockedAmount', getU64Decoder()],
    ['cliffPeriod', getU64Decoder()],
    ['unlockPeriod', getU64Decoder()],
  ]);
}

export function getVestingParamsCodec(): FixedSizeCodec<
  VestingParamsArgs,
  VestingParams
> {
  return combineCodec(getVestingParamsEncoder(), getVestingParamsDecoder());
}
