/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type VestingSchedule = {
  totalLockedAmount: bigint;
  cliffPeriod: bigint;
  unlockPeriod: bigint;
  startTime: bigint;
  /** Total allocated share amount of the base token, not greater than total_locked_amount */
  allocatedShareAmount: bigint;
};

export type VestingScheduleArgs = {
  totalLockedAmount: number | bigint;
  cliffPeriod: number | bigint;
  unlockPeriod: number | bigint;
  startTime: number | bigint;
  /** Total allocated share amount of the base token, not greater than total_locked_amount */
  allocatedShareAmount: number | bigint;
};

export function getVestingScheduleEncoder(): FixedSizeEncoder<VestingScheduleArgs> {
  return getStructEncoder([
    ['totalLockedAmount', getU64Encoder()],
    ['cliffPeriod', getU64Encoder()],
    ['unlockPeriod', getU64Encoder()],
    ['startTime', getU64Encoder()],
    ['allocatedShareAmount', getU64Encoder()],
  ]);
}

export function getVestingScheduleDecoder(): FixedSizeDecoder<VestingSchedule> {
  return getStructDecoder([
    ['totalLockedAmount', getU64Decoder()],
    ['cliffPeriod', getU64Decoder()],
    ['unlockPeriod', getU64Decoder()],
    ['startTime', getU64Decoder()],
    ['allocatedShareAmount', getU64Decoder()],
  ]);
}

export function getVestingScheduleCodec(): FixedSizeCodec<
  VestingScheduleArgs,
  VestingSchedule
> {
  return combineCodec(getVestingScheduleEncoder(), getVestingScheduleDecoder());
}
